@extends('dashboard.messaging.layout')
@section('messaging-content')
<section class="panel"><h2>Siapkan informasi baru</h2><form class="messaging-form" method="POST" action="{{ route('dashboard.messaging.campaigns.store') }}" data-compose data-recipients-url="{{ route('dashboard.messaging.recipients') }}" data-preview-url="{{ route('dashboard.messaging.campaigns.preview') }}" data-selected="{{ json_encode(old('contactIds', [])) }}">@csrf
<input type="hidden" name="request_uuid" value="{{ $requestUuid }}"><input type="hidden" name="previewToken" value=""><input type="hidden" name="templateId" value="{{ old('templateId') }}">
<div class="messaging-grid"><label>Nama campaign<input name="name" required minlength="2" maxlength="120" value="{{ old('name') }}"></label><label>Ukuran batch<input type="number" name="batchSize" min="1" max="50" value="{{ old('batchSize', 10) }}" required></label></div>
<details><summary>Gunakan template tersimpan</summary><div data-template-list></div><button type="button" class="btn btn-secondary" data-template-more hidden>Template berikutnya</button></details>
<label>Isi pesan<textarea name="content" rows="9" required maxlength="4000">{{ old('content') }}</textarea><small class="muted">Gunakan @{{nama}} untuk personalisasi. Template yang dipakai tidak berubah saat isi di sini diedit.</small></label>
<div class="messaging-options"><label><input type="checkbox" name="useBanner" value="1" @checked(old('useBanner', false))> Gunakan banner default</label><label><input type="checkbox" name="useInteractiveCta" value="1" @checked(old('useInteractiveCta', false)) @disabled(!$settings['interactiveCtaEnabled'])> Tombol tindakan</label></div>
@if(!$settings['interactiveCtaEnabled'])<small class="muted">Tombol tindakan belum diaktifkan pada server.</small>@endif
<img class="messaging-banner" src="{{ $settings['defaultBannerUrl'] }}" alt="Banner default" data-banner hidden loading="lazy">
<fieldset><legend>Penerima: <strong data-selected-count>0</strong> dipilih</legend><div class="messaging-search"><input type="search" data-recipient-search placeholder="Cari nama atau nomor"><button type="button" class="btn btn-secondary" data-recipient-load>Cari</button><button type="button" class="btn btn-secondary" data-select-page>Pilih halaman ini</button><button type="button" class="btn btn-secondary" data-clear-selection>Kosongkan</button></div><div data-recipient-list></div><div class="actions"><button type="button" class="btn btn-secondary" data-recipient-prev>Sebelumnya</button><span data-recipient-page></span><button type="button" class="btn btn-secondary" data-recipient-next>Berikutnya</button></div></fieldset>
<div data-contact-inputs></div><div class="messaging-alert" data-compose-error hidden role="alert"></div><section class="messaging-preview" data-final-preview hidden aria-live="polite"></section>
<div class="actions"><button type="button" class="btn btn-secondary" data-preview>Tinjau pesan</button><button class="btn btn-primary" data-create disabled>Buat draft</button><a class="btn btn-secondary" href="{{ route('dashboard.messaging.campaigns') }}">Batal</a></div><p class="muted">Draft tidak langsung dikirim. Mulai pengiriman melalui detail campaign setelah ditinjau.</p>
</form></section>
@endsection
